# Generated by Django 3.0 on 2019-12-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('subject', models.CharField(max_length=1000, verbose_name='Asunto')),
                ('message', models.TextField(max_length=20000, verbose_name='Mensaje')),
            ],
        ),
    ]
